-- ============================================================
-- 1. posts 테이블
-- ============================================================
create table if not exists posts (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  title     text not null,
  content   text not null,
  author_name text,
  views     integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table posts enable row level security;

create policy "posts_select" on posts for select using (true);
create policy "posts_insert" on posts for insert with check (auth.uid() = user_id);
create policy "posts_update" on posts for update using (auth.uid() = user_id);
create policy "posts_delete" on posts for delete using (auth.uid() = user_id);

-- ============================================================
-- 2. comments 테이블
-- ============================================================
create table if not exists comments (
  id        bigint generated by default as identity primary key,
  post_id   bigint references posts on delete cascade not null,
  user_id   uuid references auth.users on delete cascade not null,
  content   text not null,
  author_name text,
  created_at timestamptz default now()
);

alter table comments enable row level security;

create policy "comments_select" on comments for select using (true);
create policy "comments_insert" on comments for insert with check (auth.uid() = user_id);
create policy "comments_delete" on comments for delete using (auth.uid() = user_id);

-- ============================================================
-- 3. increment_views RPC 함수 (조회수 증가)
-- ============================================================
create or replace function increment_views(post_id bigint)
returns void
language sql
security definer
as $$
  update posts set views = views + 1 where id = post_id;
$$;
