-- Migration: comments 테이블 생성
create table if not exists comments (
  id          bigint generated by default as identity primary key,
  post_id     bigint references posts on delete cascade not null,
  user_id     uuid   references auth.users on delete cascade not null,
  content     text   not null,
  author_name text,
  created_at  timestamptz default now()
);

alter table comments enable row level security;

create policy "comments_select" on comments for select using (true);
create policy "comments_insert" on comments for insert with check (auth.uid() = user_id);
create policy "comments_delete" on comments for delete using (auth.uid() = user_id);
