-- Migration: posts 테이블 생성
create table if not exists posts (
  id          bigint generated by default as identity primary key,
  user_id     uuid    references auth.users on delete cascade not null,
  title       text    not null,
  content     text    not null,
  author_name text,
  category    text    not null default 'free'
              check (category in ('notice', 'free', 'qna')),
  views       integer default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

alter table posts enable row level security;

create policy "posts_select" on posts for select using (true);
create policy "posts_insert" on posts for insert with check (auth.uid() = user_id);
create policy "posts_update" on posts for update using (auth.uid() = user_id);
create policy "posts_delete" on posts for delete using (auth.uid() = user_id);
